apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: test-secret
    creationPolicy: Owner
  data:
  - secretKey: test-key
    remoteRef:
      key: test-secret