apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dimo-node-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    dimo_admin:  # database owner
    - superuser
    - createdb
    dimo_owner: []  # role for application foo
  databases:
    dimo: dimo_owner  # dbname: owner
  postgresql:
    version: "15"