apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-apple-auth-secret
  namespace: dex
spec:
  data:
  - remoteRef:
      key: dex/dex/apple/private_key
    secretKey: authkey.p8
  - remoteRef:
      key: dex/dex/apple/client_id
    secretKey: APPLE_CLIENT_ID
  - remoteRef:
      key: dex/dex/apple/key_id
    secretKey: APPLE_KEY_ID
  - remoteRef:
      key: dex/dex/apple/team_id
    secretKey: APPLE_TEAM_ID
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: dex-apple-auth-secret
    template:
      metadata: {}